/*
 * CV API
 * CV Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qpact.cvviewer.model.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.util.UUID;

@Data
@Entity
@Table(name="CV")
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class CvDo {
  @Id
  @Column(name="ID")
  @GeneratedValue(strategy = GenerationType.AUTO)
  private UUID id;

  @Column(name="EMAIL")
  @EqualsAndHashCode.Include
  private String email;

  @Column(name="NAME")
  private String name;

  @Column(name="BIRTHDATE")
  private String birthdate;

  @Column(name="PHONE_NUMBER")
  private String phoneNumber;

  @Column(name="DESCRIPTION")
  private String description;
}

