server:
  port: 8080
  servlet.context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa.hibernate.ddl-auto: update
  h2.console.enabled: true

management.endpoints.web.exposure.include: info, health, mappings