/*
 * CV API
 * CV Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qpact.cvviewer.model;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;

@Data
@Entity
public class Cv {
  @Id
  private String id = null;

  private String name = null;

  private String birthdate = null;

  private String phoneNumber = null;

  private String email = null;

  private String description = null;
}

